dependencies:
- name: acme-system-watcher
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: acme-trading-backend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: acme-trading-frontend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: test654456
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
